pipeline {
  agent any

  parameters {
    string(name: 'IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag to scan')
  }

  environment {
    DOCKERHUB_REPO = "ahmedlebshten/url-shortener"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Trivy Image Scan') {
      steps {
        sh """
        echo "🔍 Scanning Docker Image using Trivy..."
        docker run --rm aquasec/trivy:latest image ${DOCKERHUB_REPO}:${params.IMAGE_TAG}
        echo "✅ Trivy Image Scan Completed!"
        """
      }
    }

    stage('Gitleaks Scan') {
      steps {
        sh '''
          echo "🔍 Cloning and Scanning CI Repo with Gitleaks..."

          rm -rf ci
          git clone https://github.com/Ahmedlebshten/Jenkins-CI-Pipeline.git ci

          docker run --rm -v $PWD/ci:/repo zricethezav/gitleaks:latest detect --source=/repo || true

          echo "✅ Gitleaks Scan Finished!"
        '''
      }
    }

    stage('SonarQube Scan') {
      environment {
        SONAR_HOST_URL = "http://98.93.77.199:9100"
        SONAR_TOKEN    = credentials('sonar-token')
      }
      steps {
        sh '''
          echo "🔍 Running SonarQube Scan..."

          rm -rf ci
          git clone https://github.com/Ahmedlebshten/Jenkins-CI-Pipeline.git ci
          cd ci

          sonar-scanner \
            -Dsonar.projectKey=ci \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN || true

          echo "✅ SonarQube Scan Finished!"
        '''
      }
    }
  }

  post {
    success { echo "Security scans passed for image tag: ${params.IMAGE_TAG}" }
    failure { echo "Security scans failed!" }
  }
}
