pipeline {
  agent any

  parameters {
    string(name: 'IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag to scan')
  }

  environment {
    DOCKERHUB_REPO = "ahmedlebshten/url-shortener"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Gitleaks Scan') {
      steps {
        sh '''
          echo "🔍 Cloning and Scanning CI Repo with Gitleaks..."

          rm -rf ci
          git clone https://github.com/Ahmedlebshten/Jenkins-CI-Pipeline.git ci

          # لو مش محتاج history استخدم --no-git عشان تمنع error بتاع git
          docker run --rm -v $PWD/ci:/repo zricethezav/gitleaks:latest detect --source=/repo --no-git || true

          echo "✅ Gitleaks Scan Finished!"
        '''
      }
    }

    stage('SonarQube Scan') {
      environment {
        SONAR_HOST_URL = "http://54.147.28.81:9100"
        SONAR_TOKEN    = credentials('sonar-token')
      }
      steps {
        withSonarQubeEnv('SonarQube') {            // اسم السيرفر من Manage Jenkins → SonarQube servers
          script {
            def scannerHome = tool 'sonar-scanner' // اسم الـ Scanner من Global Tool Configuration
            sh """
              echo "🔍 Running SonarQube Scan..."

              rm -rf ci
              git clone https://github.com/Ahmedlebshten/Jenkins-CI-Pipeline.git ci
              cd ci

              ${scannerHome}/bin/sonar-scanner \
                -Dsonar.projectKey=ci \
                -Dsonar.sources=. \
                -Dsonar.host.url=${SONAR_HOST_URL} \
                -Dsonar.login=${SONAR_TOKEN} || true

              echo "✅ SonarQube Scan Finished!"
            """
          }
        }
      }
    }

    stage('Trivy Image Scan') {
      steps {
        sh """
          echo "🔍 Scanning Docker Image using Trivy..."

          # استخدم Docker daemon المحلي (الصورة لسه مبنية في CI job)
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image ${DOCKERHUB_REPO}:${params.IMAGE_TAG}

          echo "✅ Trivy Image Scan Completed!"
        """
      }
    }
  }

  post {
    success { echo "Security scans passed for image tag: ${params.IMAGE_TAG}" }
    failure { echo "Security scans failed!" }
  }
}
